[plugin]
id = "io.tsukasa.millennium.external-data-sources"
name = "External Data Sources"
author = "tsukasa"
version = "0.0.5"
description = "Adds external data sources like RSS and Atom news for non-Steam games."

[assets]
resources = ["LICENSE", "THIRD_PARTY_NOTICES.md"]

[backend]
entry = "backend/main.lua"
sources = ["backend/**/*.lua"]

[frontend]
entry = "frontend/index.tsx"

[compiler]
output_path = "dist/io.tsukasa.millennium.external-data-sources.star"

[dev]
auto_restart = true
reload_steamui_when = "both"
